FROM python:3.9.6

WORKDIR C:\Users\Acer\Documents\Studium\PhD\01_MA_preterm_gene-expression\ENIGMA


COPY requirements.txt ./


RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python", "./test.py" ]